[package]
name = "xclient_call_mul"
version = "0.1.0"
authors = ["smallnest <smallnest@gmail.com>"]
edition = "2018"

[dependencies]
rpcx = { git = "https://github.com/smallnest/rpcx-rs" }
mul_model =  { path = "../mul_model" }