[package]
name = "client_call_proto"
version = "0.1.3"
authors = ["smallnest <smallnest@gmail.com>"]
edition = "2018"

[dependencies]
rpcx = { git = "https://github.com/smallnest/rpcx-rs" }
mul_model_proto =  { path = "../mul_model_proto" }